const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

const pets = [
  {
    id: "1",
    title: "Luna the Labrador",
    description: "Luna is a playful 3-year-old golden Labrador who loves fetch and swimming. She's great with kids and has a gentle, affectionate personality. Her favorite hobby is chasing butterflies in the backyard.",
    imageUrl: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Labrador Retriever",
    age: 3,
    gender: "Female",
    weight: "28kg",
    location: "San Francisco, CA",
    status: "Available",
    tags: ["playful", "friendly", "great with kids"],
    fileSizeKb: 420,
    createdAt: "2024-01-15T08:30:00Z",
  },
  {
    id: "2",
    title: "Oliver the Orange Tabby",
    description: "Oliver is a calm and curious 2-year-old orange tabby cat. He enjoys lounging in sunny spots and watching birds through the window. He's indoor-trained and loves a good chin scratch.",
    imageUrl: "https://images.pexels.com/photos/2071873/pexels-photo-2071873.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Cat",
    breed: "Domestic Shorthair",
    age: 2,
    gender: "Male",
    weight: "5kg",
    location: "Portland, OR",
    status: "Available",
    tags: ["calm", "curious", "indoor"],
    fileSizeKb: 385,
    createdAt: "2024-02-03T10:15:00Z",
  },
  {
    id: "3",
    title: "Max the German Shepherd",
    description: "Max is an intelligent and loyal 4-year-old German Shepherd. He's well-trained, knows over 20 commands, and excels at agility. He needs an active family who can keep up with his energy.",
    imageUrl: "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "German Shepherd",
    age: 4,
    gender: "Male",
    weight: "35kg",
    location: "Austin, TX",
    status: "Available",
    tags: ["intelligent", "loyal", "active"],
    fileSizeKb: 510,
    createdAt: "2024-01-28T14:45:00Z",
  },
  {
    id: "4",
    title: "Bella the Beagle",
    description: "Bella is a sweet 1-year-old Beagle puppy with the most expressive eyes you've ever seen. She's still learning the ropes but picks up tricks quickly. Perfect for first-time dog owners.",
    imageUrl: "https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Beagle",
    age: 1,
    gender: "Female",
    weight: "10kg",
    location: "Chicago, IL",
    status: "Available",
    tags: ["puppy", "sweet", "trainable"],
    fileSizeKb: 360,
    createdAt: "2024-03-10T09:00:00Z",
  },
  {
    id: "5",
    title: "Whiskers the Persian",
    description: "Whiskers is a dignified 5-year-old Persian cat with a luxurious coat and a regal demeanor. He prefers quiet environments and would be happiest as the only pet. Daily grooming is a must.",
    imageUrl: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Cat",
    breed: "Persian",
    age: 5,
    gender: "Male",
    weight: "6kg",
    location: "New York, NY",
    status: "Available",
    tags: ["regal", "quiet", "grooming-intensive"],
    fileSizeKb: 445,
    createdAt: "2024-02-20T11:30:00Z",
  },
  {
    id: "6",
    title: "Rocky the Rottweiler",
    description: "Rocky is a gentle giant — a 5-year-old Rottweiler who thinks he's a lap dog. Despite his imposing size, he's deeply affectionate and protective. He's had obedience training and is great on a leash.",
    imageUrl: "https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Rottweiler",
    age: 5,
    gender: "Male",
    weight: "50kg",
    location: "Denver, CO",
    status: "Available",
    tags: ["gentle", "protective", "trained"],
    fileSizeKb: 490,
    createdAt: "2024-01-05T16:00:00Z",
  },
  {
    id: "7",
    title: "Nala the Siamese",
    description: "Nala is a vocal and social 3-year-old Siamese cat who will talk your ear off. She bonds deeply with her humans and thrives on interaction. She gets lonely easily and would love a companion.",
    imageUrl: "https://images.pexels.com/photos/416160/pexels-photo-416160.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Cat",
    breed: "Siamese",
    age: 3,
    gender: "Female",
    weight: "4.5kg",
    location: "Seattle, WA",
    status: "Available",
    tags: ["vocal", "social", "affectionate"],
    fileSizeKb: 375,
    createdAt: "2024-03-01T12:00:00Z",
  },
  {
    id: "8",
    title: "Buddy the Border Collie",
    description: "Buddy is an energetic 2-year-old Border Collie who thrives on mental stimulation. He's incredibly smart, can learn new tricks in minutes, and loves herding anything that moves — including children!",
    imageUrl: "https://images.pexels.com/photos/1829545/pexels-photo-1829545.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Border Collie",
    age: 2,
    gender: "Male",
    weight: "22kg",
    location: "Boston, MA",
    status: "Available",
    tags: ["energetic", "intelligent", "herding"],
    fileSizeKb: 430,
    createdAt: "2024-02-14T08:00:00Z",
  },
  {
    id: "9",
    title: "Mango the Cockatiel",
    description: "Mango is a cheerful 4-year-old yellow cockatiel who loves to whistle tunes and mimic sounds. He's hand-tamed and enjoys being held. He'll sing you awake every morning with his favorite melody.",
    imageUrl: "https://images.pexels.com/photos/1618606/pexels-photo-1618606.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Bird",
    breed: "Cockatiel",
    age: 4,
    gender: "Male",
    weight: "90g",
    location: "Miami, FL",
    status: "Available",
    tags: ["singing", "hand-tamed", "cheerful"],
    fileSizeKb: 310,
    createdAt: "2024-01-22T13:45:00Z",
  },
  {
    id: "10",
    title: "Shadow the Black Cat",
    description: "Shadow is a mysterious and elegant 6-year-old black cat who is full of surprises. Despite his aloof first impression, he becomes incredibly playful at night. He's an ace at hide and seek.",
    imageUrl: "https://images.pexels.com/photos/208984/pexels-photo-208984.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Cat",
    breed: "Domestic Shorthair",
    age: 6,
    gender: "Male",
    weight: "5.5kg",
    location: "Los Angeles, CA",
    status: "Available",
    tags: ["elegant", "mysterious", "playful"],
    fileSizeKb: 355,
    createdAt: "2024-01-08T17:30:00Z",
  },
  {
    id: "11",
    title: "Daisy the Dachshund",
    description: "Daisy is a feisty 3-year-old Dachshund with a surprisingly big bark. She loves burrowing under blankets and going on long walks. Her tiny legs carry her at surprising speeds at the dog park.",
    imageUrl: "https://images.pexels.com/photos/1789796/pexels-photo-1789796.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Dachshund",
    age: 3,
    gender: "Female",
    weight: "8kg",
    location: "Nashville, TN",
    status: "Available",
    tags: ["feisty", "cuddly", "adventurous"],
    fileSizeKb: 395,
    createdAt: "2024-03-05T10:30:00Z",
  },
  {
    id: "12",
    title: "Thor the Husky",
    description: "Thor is a striking 3-year-old Siberian Husky with piercing blue eyes. He's a natural escape artist, so a secure yard is essential. He loves cold weather, pulling sleds, and howling at the moon.",
    imageUrl: "https://images.pexels.com/photos/1457660/pexels-photo-1457660.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Siberian Husky",
    age: 3,
    gender: "Male",
    weight: "30kg",
    location: "Minneapolis, MN",
    status: "Available",
    tags: ["striking", "active", "escape-artist"],
    fileSizeKb: 540,
    createdAt: "2024-02-10T15:00:00Z",
  },
  {
    id: "13",
    title: "Cleo the Rabbit",
    description: "Cleo is a fluffy 2-year-old Holland Lop rabbit who loves to binky around her enclosure. She's litter trained and free-roams the living room under supervision. She enjoys fresh herbs and hay.",
    imageUrl: "https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Rabbit",
    breed: "Holland Lop",
    age: 2,
    gender: "Female",
    weight: "2kg",
    location: "Philadelphia, PA",
    status: "Available",
    tags: ["fluffy", "litter-trained", "gentle"],
    fileSizeKb: 280,
    createdAt: "2024-03-18T09:45:00Z",
  },
  {
    id: "14",
    title: "Zeus the Great Dane",
    description: "Zeus is a gentle giant — a 4-year-old Great Dane who stands nearly 90cm at the shoulder. Despite his enormous size, he's calm, low-energy indoors, and loves being a couch companion.",
    imageUrl: "https://images.pexels.com/photos/1787414/pexels-photo-1787414.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Great Dane",
    age: 4,
    gender: "Male",
    weight: "75kg",
    location: "Phoenix, AZ",
    status: "Available",
    tags: ["giant", "calm", "couch-companion"],
    fileSizeKb: 520,
    createdAt: "2024-01-30T11:00:00Z",
  },
  {
    id: "15",
    title: "Ginger the Guinea Pig",
    description: "Ginger is an adorable 1-year-old ginger-colored guinea pig who chatters and wheeeks whenever she hears the fridge open. She's social and would love a guinea pig companion to live with.",
    imageUrl: "https://images.pexels.com/photos/977791/pexels-photo-977791.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Small Animal",
    breed: "Guinea Pig",
    age: 1,
    gender: "Female",
    weight: "1kg",
    location: "Columbus, OH",
    status: "Available",
    tags: ["social", "vocal", "small"],
    fileSizeKb: 265,
    createdAt: "2024-03-22T14:00:00Z",
  },
  {
    id: "16",
    title: "Peanut the Pomeranian",
    description: "Peanut is a fluffy ball of energy — a 2-year-old Pomeranian who thinks he owns every room he enters. He's extremely loyal to his person and loves being the center of attention.",
    imageUrl: "https://images.pexels.com/photos/1620826/pexels-photo-1620826.jpeg?auto=compress&cs=tinysrgb&w=800",
    species: "Dog",
    breed: "Pomeranian",
    age: 2,
    gender: "Male",
    weight: "3kg",
    location: "San Diego, CA",
    status: "Available",
    tags: ["fluffy", "loyal", "attention-seeker"],
    fileSizeKb: 370,
    createdAt: "2024-02-25T16:30:00Z",
  },
];

// Deno.serve(async (req: Request) => {
//   if (req.method === "OPTIONS") {
//     return new Response(null, { status: 200, headers: corsHeaders });
//   }

//   try {
//     const url = new URL(req.url);
//     const pathParts = url.pathname.split("/").filter(Boolean);
//     const id = pathParts[pathParts.length - 1];

//     if (id && id !== "pets" && !isNaN(Number(id))) {
//       const pet = pets.find((p) => p.id === id);
//       if (!pet) {
//         return new Response(JSON.stringify({ error: "Pet not found" }), {
//           status: 404,
//           headers: { ...corsHeaders, "Content-Type": "application/json" },
//         });
//       }
//       return new Response(JSON.stringify(pet), {
//         headers: { ...corsHeaders, "Content-Type": "application/json" },
//       });
//     }

//     return new Response(JSON.stringify(pets), {
//       headers: { ...corsHeaders, "Content-Type": "application/json" },
//     });
//   } catch (err) {
//     return new Response(JSON.stringify({ error: String(err) }), {
//       status: 500,
//       headers: { ...corsHeaders, "Content-Type": "application/json" },
//     });
//   }
// });
